create table MOCK_CLOTHING_DATA (
	image VARCHAR(1000),
	item_description TEXT,
	condition VARCHAR(12),
	price DECIMAL(5,2),
	gender VARCHAR(50),
	size VARCHAR(11),
	color VARCHAR(50),
	brand VARCHAR(50),
	availability VARCHAR(50),
	seller VARCHAR(50)
);
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('https://liveinternet.ru/arcu/libero.jsp?primis=eros&in=suspendisse&faucibus=accumsan&orci=tortor&luctus=quis&et=turpis&ultrices=sed&posuere=ante&cubilia=vivamus&curae=tortor&duis=duis&faucibus=mattis&accumsan=egestas&odio=metus&curabitur=aenean', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'lightly used', 80.47, 'Female', 'extra large', 'Green', 'Topiclounge', false, 'crevey0');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('https://java.com/semper/porta/volutpat/quam.aspx?mollis=vel&molestie=ipsum&lorem=praesent&quisque=blandit&ut=lacinia&erat=erat&curabitur=vestibulum&gravida=sed&nisi=magna&at=at&nibh=nunc&in=commodo&hac=placerat&habitasse=praesent&platea=blandit&dictumst=nam&aliquam=nulla&augue=integer&quam=pede&sollicitudin=justo&vitae=lacinia&consectetuer=eget&eget=tincidunt&rutrum=eget&at=tempus&lorem=vel&integer=pede&tincidunt=morbi&ante=porttitor&vel=lorem&ipsum=id&praesent=ligula&blandit=suspendisse&lacinia=ornare&erat=consequat&vestibulum=lectus&sed=in&magna=est&at=risus&nunc=auctor&commodo=sed&placerat=tristique&praesent=in&blandit=tempus&nam=sit&nulla=amet&integer=sem&pede=fusce', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'new', 28.82, 'Male', 'small', 'Indigo', 'Devbug', true, 'acawse1');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('http://mail.ru/vel/pede/morbi/porttitor/lorem.html?ullamcorper=dapibus&augue=augue&a=vel&suscipit=accumsan&nulla=tellus&elit=nisi&ac=eu&nulla=orci&sed=mauris&vel=lacinia&enim=sapien&sit=quis&amet=libero&nunc=nullam&viverra=sit&dapibus=amet&nulla=turpis&suscipit=elementum&ligula=ligula&in=vehicula&lacus=consequat', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'refurbished', 34.83, 'Female', 'large', 'Aquamarine', 'Skibox', false, 'clade2');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('https://smh.com.au/hac/habitasse/platea/dictumst/maecenas/ut/massa.aspx?et=viverra&magnis=diam', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'used', 49.33, 'Female', 'medium', 'Orange', 'Minyx', true, 'cruckman3');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('http://ow.ly/justo/in/blandit.jpg?velit=accumsan&donec=odio&diam=curabitur&neque=convallis&vestibulum=duis&eget=consequat&vulputate=dui&ut=nec&ultrices=nisi&vel=volutpat&augue=eleifend&vestibulum=donec&ante=ut&ipsum=dolor&primis=morbi&in=vel&faucibus=lectus&orci=in&luctus=quam&et=fringilla&ultrices=rhoncus&posuere=mauris&cubilia=enim&curae=leo&donec=rhoncus&pharetra=sed&magna=vestibulum&vestibulum=sit&aliquet=amet&ultrices=cursus&erat=id&tortor=turpis&sollicitudin=integer&mi=aliquet&sit=massa&amet=id&lobortis=lobortis&sapien=convallis&sapien=tortor&non=risus&mi=dapibus&integer=augue&ac=vel&neque=accumsan&duis=tellus&bibendum=nisi&morbi=eu&non=orci&quam=mauris&nec=lacinia&dui=sapien&luctus=quis&rutrum=libero&nulla=nullam&tellus=sit&in=amet&sagittis=turpis&dui=elementum&vel=ligula&nisl=vehicula&duis=consequat&ac=morbi&nibh=a&fusce=ipsum&lacus=integer&purus=a&aliquet=nibh&at=in&feugiat=quis&non=justo&pretium=maecenas&quis=rhoncus&lectus=aliquam&suspendisse=lacus&potenti=morbi&in=quis&eleifend=tortor&quam=id', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'new', 49.76, 'Female', 'large', 'Red', 'Mycat', false, 'zcarlton4');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('https://blog.com/nullam/molestie.js?quam=nullam&turpis=varius&adipiscing=nulla&lorem=facilisi&vitae=cras&mattis=non&nibh=velit&ligula=nec&nec=nisi&sem=vulputate&duis=nonummy&aliquam=maecenas&convallis=tincidunt&nunc=lacus&proin=at&at=velit&turpis=vivamus&a=vel&pede=nulla&posuere=eget&nonummy=eros&integer=elementum&non=pellentesque&velit=quisque&donec=porta&diam=volutpat&neque=erat&vestibulum=quisque&eget=erat&vulputate=eros&ut=viverra&ultrices=eget&vel=congue', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'lightly used', 86.87, 'Male', 'small', 'Pink', 'Ozu', true, 'bfysh5');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('http://forbes.com/neque.html?sem=rhoncus&mauris=aliquam&laoreet=lacus&ut=morbi&rhoncus=quis&aliquet=tortor&pulvinar=id&sed=nulla&nisl=ultrices&nunc=aliquet&rhoncus=maecenas&dui=leo&vel=odio&sem=condimentum&sed=id&sagittis=luctus&nam=nec&congue=molestie&risus=sed&semper=justo&porta=pellentesque&volutpat=viverra&quam=pede&pede=ac&lobortis=diam&ligula=cras&sit=pellentesque&amet=volutpat&eleifend=dui&pede=maecenas&libero=tristique&quis=est&orci=et&nullam=tempus&molestie=semper&nibh=est&in=quam&lectus=pharetra&pellentesque=magna&at=ac&nulla=consequat&suspendisse=metus&potenti=sapien&cras=ut&in=nunc&purus=vestibulum&eu=ante&magna=ipsum&vulputate=primis&luctus=in&cum=faucibus&sociis=orci&natoque=luctus&penatibus=et&et=ultrices&magnis=posuere&dis=cubilia&parturient=curae&montes=mauris&nascetur=viverra&ridiculus=diam&mus=vitae&vivamus=quam&vestibulum=suspendisse&sagittis=potenti&sapien=nullam&cum=porttitor&sociis=lacus&natoque=at&penatibus=turpis&et=donec&magnis=posuere&dis=metus&parturient=vitae&montes=ipsum&nascetur=aliquam&ridiculus=non&mus=mauris&etiam=morbi&vel=non&augue=lectus&vestibulum=aliquam&rutrum=sit&rutrum=amet', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'lightly used', 77.08, 'Female', 'small', 'Khaki', 'Einti', true, 'mshufflebotham6');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('https://reddit.com/vel/augue/vestibulum/rutrum/rutrum/neque.html?mi=risus&integer=dapibus&ac=augue&neque=vel&duis=accumsan&bibendum=tellus&morbi=nisi&non=eu&quam=orci&nec=mauris&dui=lacinia&luctus=sapien&rutrum=quis&nulla=libero&tellus=nullam&in=sit&sagittis=amet&dui=turpis&vel=elementum&nisl=ligula&duis=vehicula&ac=consequat&nibh=morbi&fusce=a', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'refurbished', 73.86, 'Male', 'small', 'Khaki', 'Fivechat', true, 'toloshkin7');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('http://rediff.com/mus/vivamus/vestibulum/sagittis/sapien/cum.aspx?quam=lectus&sapien=pellentesque&varius=eget&ut=nunc&blandit=donec&non=quis&interdum=orci&in=eget&ante=orci&vestibulum=vehicula&ante=condimentum&ipsum=curabitur&primis=in&in=libero&faucibus=ut&orci=massa&luctus=volutpat&et=convallis&ultrices=morbi&posuere=odio&cubilia=odio&curae=elementum&duis=eu&faucibus=interdum&accumsan=eu&odio=tincidunt&curabitur=in&convallis=leo&duis=maecenas&consequat=pulvinar&dui=lobortis&nec=est&nisi=phasellus&volutpat=sit&eleifend=amet&donec=erat&ut=nulla&dolor=tempus&morbi=vivamus&vel=in&lectus=felis&in=eu&quam=sapien&fringilla=cursus&rhoncus=vestibulum&mauris=proin&enim=eu&leo=mi&rhoncus=nulla&sed=ac&vestibulum=enim&sit=in&amet=tempor&cursus=turpis&id=nec&turpis=euismod&integer=scelerisque&aliquet=quam&massa=turpis&id=adipiscing&lobortis=lorem&convallis=vitae&tortor=mattis&risus=nibh&dapibus=ligula&augue=nec&vel=sem&accumsan=duis&tellus=aliquam&nisi=convallis&eu=nunc&orci=proin&mauris=at&lacinia=turpis&sapien=a&quis=pede&libero=posuere&nullam=nonummy&sit=integer&amet=non&turpis=velit&elementum=donec&ligula=diam&vehicula=neque&consequat=vestibulum&morbi=eget&a=vulputate&ipsum=ut&integer=ultrices&a=vel&nibh=augue', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'new', 92.77, 'Female', 'medium', 'Green', 'DabZ', false, 'prands8');
insert into MOCK_CLOTHING_DATA (image, item_description, condition, price, gender, size, color, brand, availability, seller) values ('http://apple.com/nulla/dapibus/dolor/vel.js?pretium=pede&iaculis=posuere&diam=nonummy&erat=integer&fermentum=non&justo=velit&nec=donec&condimentum=diam&neque=neque&sapien=vestibulum&placerat=eget&ante=vulputate&nulla=ut&justo=ultrices&aliquam=vel&quis=augue&turpis=vestibulum&eget=ante&elit=ipsum&sodales=primis&scelerisque=in&mauris=faucibus&sit=orci&amet=luctus&eros=et&suspendisse=ultrices&accumsan=posuere&tortor=cubilia&quis=curae&turpis=donec&sed=pharetra&ante=magna&vivamus=vestibulum&tortor=aliquet&duis=ultrices&mattis=erat&egestas=tortor&metus=sollicitudin&aenean=mi&fermentum=sit&donec=amet&ut=lobortis&mauris=sapien&eget=sapien&massa=non&tempor=mi&convallis=integer&nulla=ac&neque=neque&libero=duis&convallis=bibendum&eget=morbi&eleifend=non', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'refurbished', 49.63, 'Female', 'small', 'Turquoise', 'Realbridge', true, 'omacdaid9');
